### ISSUE TITLE
Demo github page not found.

### ISSUE THREAD

**Issue by selyunin** [annegentle/create-demo#10]
Hi,
First, very nice article you wrote at:
https://www.docslikecode.com/articles/github-pages-python-sphinx

Is it possible to see web-generated docs in action i.e. sphinx generated pages on the github pages website on:
https://annegentle.github.io/create-demo

The github action for your last merge commit `80a8f69` finishes successfully on the master branch with a message:
```Your website is ready at https://annegentle.github.io/create-demo```

But when I try to access the URL, I get 404 error.

Recap: why web-page on github pages i.e. https://annegentle.github.io/create-demo is not available?

**Comment by PabloAlexis611** [comment]
I confirm...
<img width="617" alt="image" src="https://user-images.githubusercontent.com/28517429/97122372-c43f0980-16fb-11eb-851a-984518b447c9.png">

**Comment by annegentle** [comment]
Thanks for bringing this Issue to my attention! Investigating now... and will update `master` default branch name to `main` while I'm at it.

**Comment by annegentle** [comment]
Okay, looks like I'll need to update to use GitHub actions, and I'll go through this post: https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/ to fix this 404 error. I'll post here when I get it working again.

**Comment by PabloAlexis611** [comment]
Interestingly enough, I got this thing working at one of my repos at https://github.com/PabloAlexis611/DocumentationProject/.
You can see the GitHub Pages deployments at https://github.com/PabloAlexis611/DocumentationProject/deployments.
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/28517429/97239601-61fd0c00-17c2-11eb-96fe-63b7097bfb16.png">

I didn't have to use GitHub's actions for it (at least not directly, afaik). 🤔 

Should be live at https://pabloalexis611.github.io/DocumentationProject/index.html

**Comment by annegentle** [comment]
Interesting! I got it working again using GitHub actions, but now I'm wondering if that was the fix or simply switching the branch it builds from. I might switch the build branch again and see if it still works. Thanks for letting me know.

**Comment by annegentle** [comment]
Fixed, closing Issue.
